### ISSUE TITLE
Ability to add a carousel.

### ISSUE THREAD

**Issue by adampatterson** [VolgaIgor/editorjs-gallery#1]
It would be nice to have the option to flag a Gallery block as a carousel.

**Comment by VolgaIgor** [comment]
> It would be nice to have the option to flag a Gallery block as a carousel.

Hello!
I am sorry that i not answering so long, I didn't see the message.

If I understand correctly, you want the tool to be displayed in the list as "Carousel", not as "Gallery".
You can do this with the standard editor features: https://editorjs.io/i18n/

Need to add this code to the config:
```js
i18n: {
    messages: {
        toolNames: {
            'Gallery': 'Carousel'
        }
    }
}
```

**Comment by adampatterson** [comment]
Hello @VolgaIgor sorry no, 

In my implementation I am using the gallery in an article. I thought it would also be nice to have the option to insert a Carouse. 

The admin interface would be basically identical but when saving the data I'd need a way to tell if I inserted a gallery or a carousel. 

Hope that helps.

**Comment by VolgaIgor** [comment]
@adampatterson
I still don't fully understand your idea) What is "Gallery", what is "Carousel"?

Now the module has additional switches, "slider" and "fit". I meant by them that "slider" is horizontally scrolling slides with pictures, and "fit" is image tiles: 
![изображение_2023-06-28_115543058](https://github.com/VolgaIgor/editorjs-gallery/assets/43250768/3fcfcd68-958e-4fbe-9b45-b2d8e8d1cd58)
Readme says about them, maybe you need it? Titles "Slider" and "Fit" can also be changed with the internationalization tools of the editor.

Or maybe you want two blocks with the same functionality, but with different IDs. Then you just need to include them twice in the configuration with different IDs:
```js
gallery: {
    class: ImageGallery,
},
carousel: {
    class: ImageGallery,
}
```

**Comment by adampatterson** [comment]
Thanks @VolgaIgor, I did not see that in the readme but that is exactly what I want.

I call sliders carousels 😂
