### ISSUE TITLE
Usability suggestions

### ISSUE THREAD

**Issue by adampatterson** [VolgaIgor/editorjs-gallery#2]
I'm very slow and implementing Editor JS 😂

1) your plugin is really the only one that supports multiple images properly
2) I love the fact that you have a Gallery and Carousel

The only thing I am trying to make better or would love to see is a clear indication of what each block is while editing content.

If you add the block as a slider, you don't know it's a slider.
If you change it to Fit, you don't know it's a gallery.

I have customized the languages of the caption and button text, which does work really well, except now I have 2 blocks that have the ability to become a Slider or a Gallery so the context is wrong.

```
gallery: {
    class: ImageGallery,
    config: {
        captionPlaceholder: 'Gallery Caption',
        buttonContent: 'Add an image to the Gallery',
    },
},
carousel: {
    class: ImageGallery,
    config: {
        captionPlaceholder: 'Carousel Caption',
        buttonContent: 'Add an image to the Carousel',
    },
},
```

It might be a lot more straightforward if the Tune name was displayed above the block like this.

![image](https://github.com/VolgaIgor/editorjs-gallery/assets/31537/9c93d585-4c70-4bd7-ae1e-5e1d8cf69828)

Lastly, if it would be possible to add Internationalization support for the Tune names that should complete my wish list 😂

I'm using Editor.JS and your plugin inside of a kind of blog editor that will have a Media focus.

As a note I have forked the repo and tried to make the modification but working with the package locally and trying to build the app has been tricky. I had it working at one point and I think updated Node and that broke the link and my project that uses Vite / Rollup seems to have issues with packages that are symlink folders.

Any tips for working on the package locally?  There's a possibility I can make these changes and submit a pull request if you like.

**Comment by VolgaIgor** [comment]
Hello!
Thank you for your useful comments and suggestions!

I think I can add internationalization in the nearest future. In addition, I think it’s worth adding the option to disable tunes for a two block use case.

But need to think about find a better place to add the signature of the current tune)

**Comment by adampatterson** [comment]
Thanks so much 😄

**Comment by adampatterson** [comment]
Hey @VolgaIgor 

I attempted to make this change myself but for the life of me can't figure out how to get the tune value passed into the UI.

I added a UI element that's essentially a heading that I had planned to display the tune value.

Maybe I'm doing it wrong, It might be possible to do it with CSS if the tune can update a class name or something on the block wrapper.

I'm terrible with javascript though.

**Comment by VolgaIgor** [comment]
Hello! Sorry it's been so long, I've only just got time now.
* I fixed the build packages, now you should be building the project without problems
* I added the ability to remove existing tune by inserting in the config `actions: []`, so you can have two versions of the plugin without any problems
* You can change the name of the tune using the standard EditorJS internationalization tools: 
https://github.com/VolgaIgor/editorjs-gallery?tab=readme-ov-file#config-params
@adampatterson

**Comment by adampatterson** [comment]
Thanks so much, when I get a chance I'll pull the latest version and update my app!
